#!/usr/bin/env python3
"""
NVT protein MD workflow manager for AMBER.

Commands
--------
  python run_upto_NVT.py setup  [--config config.yaml] [--mode MODE] [--submit]
  python run_upto_NVT.py submit [--config config.yaml] [--mode MODE]

  setup   Generate all input and job scripts.
          Pass --submit to also launch immediately after.
  submit  Submit existing scripts without regenerating files.
          Use this after manually editing generated scripts.

Modes
-----
  cluster  (default) SLURM; master job runs stages 00-03, then chains
           NVT chunk jobs via sbatch.
  local    No SLURM.  Generates run_local for a single-GPU workstation.
"""

import argparse
import math
import re
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

REPL_ROOT = Path(__file__).resolve().parent


# =============================================================================
# AMBER input templates
# =============================================================================

_MIN_TEMPLATE = """\
Initial minimization
 &cntrl
  imin   = 1,
  maxcyc = {maxcyc},
  ncyc   = {ncyc},
  ntb    = 1,
  ntxo   = 1,
  cut    = {cut},
  iwrap  = 1
 /
"""

_HEAT_TEMPLATE = """\
Stage 2 heating on GPU 1K to {temp0}K
 &cntrl
  imin=0, irest=0, ntx=1,
  nstlim={nstlim}, dt={dt},
  ntb=1, ntp=0,
  ntc=2, ntf=2, ntt=3,
  ntpr=1000, ntwr=1000, ntwx=1000,
  ntr=1,
  restraintmask='@CA,C,N,O,H &!:WAT',
  restraint_wt=20.0,
  cut=10, gamma_ln=5.0,
  nmropt=1, iwrap=1, ntxo=1,
 /

&wt type='TEMP0', istep1=0, istep2={ramp_end},
  value1=1.0, value2={temp0}
/
&wt type='END'/
/
"""

_EQUIL_NPT_TEMPLATE = """\
equilibration cycle {cycle} (restrained NPT)
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim={nstlim}, dt={dt},
  ntb=2, ntp=1,
  ntc=2, ntf=2, ntt=3,
  tempi={temp}, temp0={temp},
  ntpr=1000, ntwx=1000,
  ntr=1,
  restraintmask='@CA,C,N,O,H&!:WAT',
  restraint_wt={wt:.1f},
  cut=10, gamma_ln=5.0,
  iwrap=1, ntxo=1,
 /

&wt type='END'/
DISANG = restr
"""

_EQUIL_NVT_TEMPLATE = """\
equilibration cycle 6 (unrestrained NVT)
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim={nstlim}, dt={dt},
  ntb=1, ntp=0,
  ntc=2, ntf=2, ntt=3,
  tempi={temp}, temp0={temp},
  ntpr=1000, ntwx=1000,
  cut=10, gamma_ln=5.0,
  iwrap=1, ntxo=1,
 /

&wt type='END'/
DISANG = restr
"""

_PROD_TEMPLATE = """\
NVT production
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim={nstlim}, dt={dt},
  ntb=1, ntp=0,
  ntc=2, ntf=2, ntt=3,
  tempi={temp}, temp0={temp},
  ntpr={ntpr}, ntwx={ntwx}, ntwr={ntwr},
  cut=10, gamma_ln=1.0,
  iwrap=1, ntxo=1,
 /
"""


# =============================================================================
# Run script templates  (__PLACEHOLDER__ substituted in Python, not by bash)
# =============================================================================

_RUN_GPU_TEMPLATE = """\
#!/bin/bash
#SBATCH --time=__WALLTIME_MASTER__
#SBATCH --nodes=1
#SBATCH --ntasks=__NTASKS_MASTER__
#SBATCH --gres=__GRES_MASTER__
#SBATCH --partition=__PARTITION_MASTER__
#SBATCH --job-name=__JOB_NAME__
#SBATCH --account=__ACCOUNT_MASTER__
# Master script: stages 00-03 (prep, min, heat, equil).
# Stage 04_NVT is submitted as a SLURM chain at the end.
# Generated by run_upto_NVT.py — do not edit directly.

module load __AMBER_MODULE__

cd "${SLURM_SUBMIT_DIR}"
DIR=$(pwd)

# ============================================================
# 00_prep -- topology / coordinates
# ============================================================
cd $DIR/00_prep
tleap -f leap_structure
__HMR_BLOCK__

# ============================================================
# 01_min -- energy minimization with convergence check
# ============================================================
cd $DIR/01_min
cp $DIR/00_prep/structure.rst7 structure_min_0.rst7

max_min_cycles=__MIN_CYCLES_CAP__
conv_thresh=__CONV_THRESH__
converged_cycle=0

for ((i=1; i<=${max_min_cycles}; i++)); do
    pmemd.cuda -O -i min.in -o structure_min_${i}.out -p ../00_prep/__TOPOLOGY__ \\
                            -c structure_min_$((i-1)).rst7 \\
                            -r structure_min_${i}.rst7 \\
                            -ref structure_min_$((i-1)).rst7

    min_rms=$(awk '/NSTEP[[:space:]]+ENERGY[[:space:]]+RMS[[:space:]]+GMAX/ {getline; print $3}' \\
                  structure_min_${i}.out | sort -g | head -n 1)
    converged=$(awk -v r="${min_rms:-9e99}" -v t="${conv_thresh}" \\
                'BEGIN {print (r+0 < t+0) ? 1 : 0}')
    echo "01_min cycle ${i}: RMS=${min_rms} kcal/mol/A  converged=${converged}"

    if [ "${converged}" -eq 1 ]; then
        converged_cycle=${i}; break
    fi
done

[ "${converged_cycle}" -gt 0 ] && min_cycles=${converged_cycle} || {
    echo "WARNING: 01_min did not converge in ${max_min_cycles} cycles."
    min_cycles=${max_min_cycles}
}

# ============================================================
# 02_heat
# ============================================================
cd $DIR/02_heat
pmemd.cuda -O -i heat.in -o structure_heat.out -p ../00_prep/__TOPOLOGY__ \\
                          -c $DIR/01_min/structure_min_${min_cycles}.rst7 \\
                          -r structure_heat.rst7 \\
                          -x structure_heat.nc \\
                          -ref $DIR/01_min/structure_min_${min_cycles}.rst7

# ============================================================
# 03_equil -- cycles 1-5 restrained NPT; cycle 6 unrestrained NVT
# ============================================================
cd $DIR/03_equil
cp $DIR/02_heat/structure_heat.rst7 structure_equil_0.rst7

for ((i=1; i<=6; i++)); do
    pmemd.cuda -O -i equil_${i}.in -o structure_equil_${i}.out -p ../00_prep/__TOPOLOGY__ \\
                               -c structure_equil_$((i-1)).rst7 \\
                               -r structure_equil_${i}.rst7 \\
                               -x structure_equil_${i}.nc \\
                               -ref structure_equil_$((i-1)).rst7
done

# ============================================================
# 04_NVT -- production chain
# ============================================================
cd $DIR/04_NVT
cp $DIR/03_equil/structure_equil_6.rst7 structure_NVT_0.rst7
sbatch nvt_job_1.cmd
"""

_RUN_LOCAL_TEMPLATE = """\
#!/bin/bash
# Master run script: stages 00-03 + 04_NVT on a local GPU workstation.
# Generated by run_upto_NVT.py — do not edit directly.
#
# Usage:
#   bash run_local                          # foreground
#   nohup bash run_local > run.log 2>&1 &   # background

__AMBER_SETUP__

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

# ============================================================
# 00_prep -- topology / coordinates
# ============================================================
cd "$DIR/00_prep"
log "00_prep: tleap"
tleap -f leap_structure
__HMR_BLOCK__

# ============================================================
# 01_min -- energy minimization with convergence check
# ============================================================
cd "$DIR/01_min"
cp "$DIR/00_prep/structure.rst7" structure_min_0.rst7

max_min_cycles=__MIN_CYCLES_CAP__
conv_thresh=__CONV_THRESH__
converged_cycle=0

for ((i=1; i<=${max_min_cycles}; i++)); do
    log "01_min: cycle ${i}"
    pmemd.cuda -O -i min.in -o structure_min_${i}.out -p ../00_prep/__TOPOLOGY__ \\
                            -c structure_min_$((i-1)).rst7 \\
                            -r structure_min_${i}.rst7 \\
                            -ref structure_min_$((i-1)).rst7

    min_rms=$(awk '/NSTEP[[:space:]]+ENERGY[[:space:]]+RMS[[:space:]]+GMAX/ {getline; print $3}' \\
                  structure_min_${i}.out | sort -g | head -n 1)
    converged=$(awk -v r="${min_rms:-9e99}" -v t="${conv_thresh}" \\
                'BEGIN {print (r+0 < t+0) ? 1 : 0}')
    echo "01_min cycle ${i}: RMS=${min_rms} kcal/mol/A  converged=${converged}"

    if [ "${converged}" -eq 1 ]; then
        log "01_min converged at cycle ${i}"
        converged_cycle=${i}; break
    fi
done

[ "${converged_cycle}" -gt 0 ] && min_cycles=${converged_cycle} || {
    echo "WARNING: 01_min did not converge in ${max_min_cycles} cycles."
    min_cycles=${max_min_cycles}
}

# ============================================================
# 02_heat
# ============================================================
cd "$DIR/02_heat"
log "02_heat"
pmemd.cuda -O -i heat.in -o structure_heat.out -p ../00_prep/__TOPOLOGY__ \\
                          -c "$DIR/01_min/structure_min_${min_cycles}.rst7" \\
                          -r structure_heat.rst7 \\
                          -x structure_heat.nc \\
                          -ref "$DIR/01_min/structure_min_${min_cycles}.rst7"

# ============================================================
# 03_equil -- cycles 1-5 restrained NPT; cycle 6 unrestrained NVT
# ============================================================
cd "$DIR/03_equil"
cp "$DIR/02_heat/structure_heat.rst7" structure_equil_0.rst7

for ((i=1; i<=6; i++)); do
    log "03_equil: cycle ${i}/6"
    pmemd.cuda -O -i equil_${i}.in -o structure_equil_${i}.out -p ../00_prep/__TOPOLOGY__ \\
                               -c structure_equil_$((i-1)).rst7 \\
                               -r structure_equil_${i}.rst7 \\
                               -x structure_equil_${i}.nc \\
                               -ref structure_equil_$((i-1)).rst7
done

# ============================================================
# 04_NVT -- sequential production
# ============================================================
cd "$DIR/04_NVT"
cp "$DIR/03_equil/structure_equil_6.rst7" structure_NVT_0.rst7

for ((i=1; i<=__TOTAL_CHUNKS__; i++)); do
    log "04_NVT: chunk ${i}/__TOTAL_CHUNKS__"
    pmemd.cuda -O -i prod.in \\
                  -o structure_NVT_${i}.out \\
                  -p ../00_prep/__TOPOLOGY__ \\
                  -c structure_NVT_$((i-1)).rst7 \\
                  -r structure_NVT_${i}.rst7 \\
                  -x structure_NVT_${i}.nc
done

log "All done."
"""

_NVT_JOB_TEMPLATE = """\
#!/bin/bash
#SBATCH --time=__WALLTIME_NVT__
#SBATCH --nodes=1
#SBATCH --ntasks=__NTASKS_NVT__
#SBATCH --gres=__GRES_NVT__
#SBATCH --partition=__PARTITION_NVT__
#SBATCH --job-name=NVT_j__JOB_IDX__
#SBATCH --account=__ACCOUNT_NVT__
#SBATCH --output=NVT_j__JOB_IDX__-%j.out
#SBATCH --error=NVT_j__JOB_IDX__-%j.err
# NVT production: chunks __START__ to __END__ of __TOTAL__.
# Generated by run_upto_NVT.py — do not edit directly.

module load __AMBER_MODULE__

cd "${SLURM_SUBMIT_DIR}"

for ((i=__START__; i<=__END__; i++)); do
    pmemd.cuda -O -i prod.in \\
                  -o structure_NVT_${i}.out \\
                  -p ../00_prep/__TOPOLOGY__ \\
                  -c structure_NVT_$((i-1)).rst7 \\
                  -r structure_NVT_${i}.rst7 \\
                  -x structure_NVT_${i}.nc
done
__NEXT_JOB__
"""


# =============================================================================
# Script generators
# =============================================================================

def _gen_run_gpu(cfg: dict, topology: str) -> str:
    slurm = cfg["slurm"]["master"]
    hmr_block = "cpptraj -i HMR.ccptraj" if cfg.get("use_hmr", True) else "# HMR disabled"
    return (
        _RUN_GPU_TEMPLATE
        .replace("__WALLTIME_MASTER__", str(slurm.get("time", "1-00:00:00")))
        .replace("__NTASKS_MASTER__", str(slurm.get("ntasks", 1)))
        .replace("__GRES_MASTER__", str(slurm.get("gres", "gpu:1")))
        .replace("__PARTITION_MASTER__", str(slurm.get("partition", "gpu")))
        .replace("__JOB_NAME__", str(cfg.get("job_name", "NVT")))
        .replace("__ACCOUNT_MASTER__", str(slurm.get("account", "")))
        .replace("__AMBER_MODULE__", str(cfg["amber"]["module"]))
        .replace("__HMR_BLOCK__", hmr_block)
        .replace("__MIN_CYCLES_CAP__", str(cfg["min"]["max_cycles_cap"]))
        .replace("__CONV_THRESH__", str(cfg["min"]["convergence_threshold"]))
        .replace("__TOPOLOGY__", topology)
    )


def _gen_run_local(cfg: dict, topology: str) -> str:
    amber_home = cfg.get("amber_home", "").strip()
    amber_setup = (
        f'source "{amber_home}/amber.sh"' if amber_home
        else "# pmemd.cuda assumed to be on PATH"
    )
    hmr_block = "cpptraj -i HMR.ccptraj" if cfg.get("use_hmr", True) else "# HMR disabled"
    return (
        _RUN_LOCAL_TEMPLATE
        .replace("__AMBER_SETUP__", amber_setup)
        .replace("__HMR_BLOCK__", hmr_block)
        .replace("__MIN_CYCLES_CAP__", str(cfg["min"]["max_cycles_cap"]))
        .replace("__CONV_THRESH__", str(cfg["min"]["convergence_threshold"]))
        .replace("__TOPOLOGY__", topology)
        .replace("__TOTAL_CHUNKS__", str(cfg["total_chunks"]))
    )


def _gen_nvt_cluster_job(job_idx: int, start_chunk: int, end_chunk: int,
                          total_chunks: int, cfg: dict, topology: str) -> str:
    slurm = cfg["slurm"]["nvt"]
    next_job = f"\nsbatch nvt_job_{job_idx + 1}.cmd" if end_chunk < total_chunks else ""
    return (
        _NVT_JOB_TEMPLATE
        .replace("__WALLTIME_NVT__", str(slurm.get("time", "5-00:00:00")))
        .replace("__NTASKS_NVT__", str(slurm.get("ntasks", 1)))
        .replace("__GRES_NVT__", str(slurm.get("gres", "gpu:1")))
        .replace("__PARTITION_NVT__", str(slurm.get("partition", "gpu")))
        .replace("__JOB_IDX__", str(job_idx))
        .replace("__ACCOUNT_NVT__", str(slurm.get("account", "")))
        .replace("__AMBER_MODULE__", str(cfg["amber"]["module"]))
        .replace("__START__", str(start_chunk))
        .replace("__END__", str(end_chunk))
        .replace("__TOTAL__", str(total_chunks))
        .replace("__TOPOLOGY__", topology)
        .replace("__NEXT_JOB__", next_job)
    )


# =============================================================================
# Validation + propka
# =============================================================================

def validate_inputs(cfg: dict) -> None:
    pdb = REPL_ROOT / "00_prep" / cfg["pdb"]
    if not pdb.exists():
        sys.exit(f"ERROR: {pdb} not found.\n"
                 f"Place the PDB in {pdb.parent}/ before running setup.")
    leap_tmp = REPL_ROOT / "00_prep" / "leap_structure_tmp"
    if not leap_tmp.exists():
        sys.exit(f"ERROR: {leap_tmp} missing. Cannot generate leap_structure.")
    if cfg.get("use_hmr", True):
        hmr = REPL_ROOT / "00_prep" / "HMR.ccptraj"
        if not hmr.exists():
            sys.exit(f"ERROR: HMR requested but {hmr} not found.")
    if cfg.get("execution_mode", "cluster") == "local":
        amber_home = cfg.get("amber_home", "").strip()
        if not amber_home and not shutil.which("pmemd.cuda"):
            print("WARNING: pmemd.cuda not found on PATH and amber_home is not set.")


def run_propka(cfg: dict) -> None:
    if not cfg.get("use_propka", False):
        return
    pdb = REPL_ROOT / "00_prep" / cfg["pdb"]
    print(f"\nRunning propka on {pdb} ...")
    try:
        subprocess.check_call(
            [cfg.get("propka_path", "propka3"), pdb.name],
            cwd=str(pdb.parent),
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        sys.exit(f"ERROR: propka failed: {e}\nInstall with `pip install propka`.")
    pka = pdb.with_suffix(".pka")
    print(f"propka output: {pka}\n"
          "Inspect the .pka file and edit the PDB to set residue names\n"
          "(HID/HIE/HIP, ASH/ASP, GLH/GLU, LYN/LYS) per the predicted pKa.\n")
    input("Press Enter once the PDB is updated (Ctrl-C to abort): ")


# =============================================================================
# Setup
# =============================================================================

def _write_exe(path: Path, content: str) -> None:
    path.write_text(content)
    path.chmod(0o755)


def setup(cfg: dict, mode: str = "cluster", submit: bool = False) -> None:
    if mode not in ("cluster", "local"):
        sys.exit(f"Unknown mode '{mode}'. Choose: cluster, local.")

    use_hmr  = bool(cfg.get("use_hmr", True))
    dt       = 0.004 if use_hmr else 0.002
    topology = "structure_HMR.parm7" if use_hmr else "structure.parm7"
    temp     = float(cfg["temperature"])

    validate_inputs(cfg)
    run_propka(cfg)

    print(f"\nMode     : {mode}")
    print(f"HMR      : {use_hmr}  (dt={dt} ps, topology={topology})")
    print(f"Temp     : {temp} K")
    print(f"Chunks   : {cfg['total_chunks']} × {cfg['ns_per_chunk']} ns")
    print()
    print("Writing input files ...")

    # ---- leap_structure ------------------------------------------------
    src = REPL_ROOT / "00_prep" / "leap_structure_tmp"
    dst = REPL_ROOT / "00_prep" / "leap_structure"
    text = re.sub(r"loadpdb\s+\S+", f"loadpdb {cfg['pdb']}", src.read_text())
    dst.write_text(text)
    print(f"  wrote 00_prep/leap_structure")

    # ---- 01_min/min.in -------------------------------------------------
    min_cfg = cfg["min"]
    (REPL_ROOT / "01_min" / "min.in").write_text(
        _MIN_TEMPLATE.format(
            maxcyc=min_cfg["maxcyc"],
            ncyc=min_cfg["ncyc"],
            cut=min_cfg["cut"],
        )
    )
    print("  wrote 01_min/min.in")

    # ---- 02_heat/heat.in -----------------------------------------------
    heat_steps = int(round(float(cfg["heat"]["ps"]) / dt))
    ramp_end   = int(round(0.8 * heat_steps))
    (REPL_ROOT / "02_heat" / "heat.in").write_text(
        _HEAT_TEMPLATE.format(
            temp0=temp,
            nstlim=heat_steps,
            dt=dt,
            ramp_end=ramp_end,
        )
    )
    print("  wrote 02_heat/heat.in")

    # ---- 03_equil/equil_N.in  (cycles 1-5 NPT, cycle 6 NVT) -----------
    npt_steps = int(round(float(cfg["equil"]["npt_ns"]) * 1000.0 / dt))
    nvt_steps = int(round(float(cfg["equil"]["nvt_ns"]) * 1000.0 / dt))
    equil_dir = REPL_ROOT / "03_equil"
    for cycle in range(1, 6):
        wt = 15.0 - (cycle - 1) * 3.0   # 15, 12, 9, 6, 3
        (equil_dir / f"equil_{cycle}.in").write_text(
            _EQUIL_NPT_TEMPLATE.format(
                cycle=cycle, nstlim=npt_steps, dt=dt, temp=temp, wt=wt,
            )
        )
    (equil_dir / "equil_6.in").write_text(
        _EQUIL_NVT_TEMPLATE.format(nstlim=nvt_steps, dt=dt, temp=temp)
    )
    print("  wrote 03_equil/equil_{1..6}.in")

    # ---- 04_NVT/prod.in ------------------------------------------------
    prod_cfg   = cfg["prod"]
    prod_steps = int(round(float(cfg["ns_per_chunk"]) * 1000.0 / dt))
    (REPL_ROOT / "04_NVT" / "prod.in").write_text(
        _PROD_TEMPLATE.format(
            nstlim=prod_steps, dt=dt, temp=temp,
            ntpr=prod_cfg["ntpr"],
            ntwx=prod_cfg["ntwx"],
            ntwr=prod_cfg["ntwr"],
        )
    )
    print("  wrote 04_NVT/prod.in")

    # ---- master run script + NVT job scripts ---------------------------
    if mode == "cluster":
        _write_exe(REPL_ROOT / "run_gpu", _gen_run_gpu(cfg, topology))
        print("  wrote run_gpu")

        total_chunks  = int(cfg["total_chunks"])
        chunks_per_job = int(cfg["chunks_per_job"])
        n_jobs = math.ceil(total_chunks / chunks_per_job)
        for job_idx in range(1, n_jobs + 1):
            start = (job_idx - 1) * chunks_per_job + 1
            end   = min(job_idx * chunks_per_job, total_chunks)
            p = REPL_ROOT / "04_NVT" / f"nvt_job_{job_idx}.cmd"
            _write_exe(p, _gen_nvt_cluster_job(job_idx, start, end, total_chunks, cfg, topology))
        print(f"  wrote 04_NVT/nvt_job_{{1..{n_jobs}}}.cmd")
    else:
        _write_exe(REPL_ROOT / "run_local", _gen_run_local(cfg, topology))
        print("  wrote run_local")

    print("\nSetup complete.")

    if submit:
        _submit(cfg, mode)


# =============================================================================
# Submit
# =============================================================================

def _submit(cfg: dict, mode: str) -> None:
    if mode == "local":
        script = REPL_ROOT / "run_local"
        if not script.exists():
            sys.exit("run_local not found. Run 'setup --mode local' first.")
        log = REPL_ROOT / "run.log"
        proc = subprocess.Popen(
            ["bash", str(script)],
            stdout=log.open("w"),
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        print(f"\nLaunched run_local in background (PID {proc.pid}).")
        print(f"  log  → {log}")
        print(f"  stop → kill {proc.pid}")
    else:
        script = REPL_ROOT / "run_gpu"
        if not script.exists():
            sys.exit("run_gpu not found. Run 'setup' first.")
        if not shutil.which("sbatch"):
            sys.exit("sbatch not on PATH. Submit manually: sbatch run_gpu")
        result = subprocess.run(
            ["sbatch", "run_gpu"], capture_output=True, text=True, cwd=str(REPL_ROOT),
        )
        if result.returncode == 0:
            print(f"\n{result.stdout.strip()}")
        else:
            sys.exit(f"sbatch failed: {result.stderr.strip()}")


# =============================================================================
# Entry point
# =============================================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description="NVT protein MD workflow manager for AMBER.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--config", default="config.yaml",
        help="Configuration file (default: config.yaml)",
    )

    sub = parser.add_subparsers(dest="command", required=True)

    p_setup = sub.add_parser("setup", help="Generate all input files and run scripts")
    p_setup.add_argument(
        "--mode", default="cluster", choices=["cluster", "local"],
        help="cluster (SLURM, default) or local (single GPU workstation)",
    )
    p_setup.add_argument(
        "--submit", action="store_true",
        help="Launch run_gpu (sbatch) or run_local (bash) after generating files",
    )

    p_submit = sub.add_parser(
        "submit", help="Submit existing scripts without regenerating files",
    )
    p_submit.add_argument(
        "--mode", default="cluster", choices=["cluster", "local"],
        help="Must match the mode used during setup (default: cluster)",
    )

    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        sys.exit(f"Config file not found: {config_path}")

    with open(config_path) as fh:
        cfg = yaml.safe_load(fh)

    if args.command == "setup":
        setup(cfg, mode=args.mode, submit=args.submit)
    elif args.command == "submit":
        _submit(cfg, mode=args.mode)


if __name__ == "__main__":
    main()
